### ISSUE TITLE
Speeds are not entered reliably

### ISSUE THREAD

**Issue by Uwe4Waze** [wazers/wme-speedhelper#6]
If, when updating the speed of several segments, a segment is selected whose speed already corresponds to the value clicked on, the speeds may not be entered for all segments.
This depends on the order in which the segments are selected.
To reproduce select a segment which both (forward and reverse) speeds correspond to the speed you want to set. Then add another segment to this selection and click the speed which is already set on the first segment. The second segment will not be updated.
Looking in the browser console you will find an uncaught error:

app-cfa84b897bf5152f.js.gz:1 Uncaught InvalidStateError: Failed to update segment
    at Segments.updateSegment (app-cfa84b897bf5152f.js.gz:1:1743403)
    at Segments.updateSegment (app-cfa84b897bf5152f.js.gz:1:1714072)
    at Segments.updateSegment (app-cfa84b897bf5152f.js.gz:1:1713450)
    at userscript.html?name=WME-Speedhelper.user.js&id=9f21445a-ddb3-475b-a998-7178a09f836e:425:31
    at Array.forEach (<anonymous>)
    at clickSegmentSpeed (userscript.html?name=WME-Speedhelper.user.js&id=9f21445a-ddb3-475b-a998-7178a09f836e:424:17)
    at userscript.html?name=WME-Speedhelper.user.js&id=9f21445a-ddb3-475b-a998-7178a09f836e:391:55
    at sign.onclick (userscript.html?name=WME-Speedhelper.user.js&id=9f21445a-ddb3-475b-a998-7178a09f836e:460:26)
updateSegment @ app-cfa84b897bf5152f.js.gz:1
updateSegment @ app-cfa84b897bf5152f.js.gz:1
updateSegment @ app-cfa84b897bf5152f.js.gz:1
(anonymous) @ userscript.html?name=WME-Speedhelper.user.js&id=9f21445a-ddb3-475b-a998-7178a09f836e:425
clickSegmentSpeed @ userscript.html?name=WME-Speedhelper.user.js&id=9f21445a-ddb3-475b-a998-7178a09f836e:424
(anonymous) @ userscript.html?name=WME-Speedhelper.user.js&id=9f21445a-ddb3-475b-a998-7178a09f836e:391
sign.onclick @ userscript.html?name=WME-Speedhelper.user.js&id=9f21445a-ddb3-475b-a998-7178a09f836e:460
third_party-2a94acd5407f5a6c.js.gz:2 

This is due to the behaviour of SDK Segments.updateSegment function which throws an 'InvalidStateError' if no updated is needed.
See SDK documentation.

**Comment by GyllieGyllie** [comment]
Should be resolved in 1.0.2
